<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyDeTaiTotNghiep" Class="QLDADataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-HT2U3NT\SQLEXPRESS;Initial Catalog=QuanLyDeTaiTotNghiep;Integrated Security=True;Encrypt=False" SettingsObjectName="BUS.Properties.Settings" SettingsPropertyName="QuanLyDeTaiTotNghiepConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BoMon" Member="BoMons">
    <Type Name="BoMon">
      <Column Name="MaBoMon" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenBoMon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="BoMon_DeTai" Member="DeTais" ThisKey="MaBoMon" OtherKey="MaBoMon" Type="DeTai" />
      <Association Name="KHOA_BoMon" Member="KHOA" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="KHOA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeTai" Member="DeTais">
    <Type Name="DeTai">
      <Column Name="MaDeTai" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDeTai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NgayDeXuat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayDuyet" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaGVHuongDan" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaGVPhanBien" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaBoMon" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="DeTai_DoAnVaDiem" Member="DoAnVaDiems" ThisKey="MaDeTai" OtherKey="MaDeTai" Type="DoAnVaDiem" />
      <Association Name="BoMon_DeTai" Member="BoMon" ThisKey="MaBoMon" OtherKey="MaBoMon" Type="BoMon" IsForeignKey="true" />
      <Association Name="GiangVien_DeTai" Member="GiangVien" ThisKey="MaGVHuongDan" OtherKey="MaGiangVien" Type="GiangVien" IsForeignKey="true" />
      <Association Name="GiangVien_DeTai1" Member="GiangVien1" ThisKey="MaGVPhanBien" OtherKey="MaGiangVien" Type="GiangVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DoAnVaDiem" Member="DoAnVaDiems">
    <Type Name="DoAnVaDiem">
      <Column Name="MaDeTai" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Id" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayNopDoAn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoiDungDoAn" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DiemGVHuongDan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemGVPhanBien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemCuoiCung" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NhanXet" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NgayCham" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaNhom" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="DeTai_DoAnVaDiem" Member="DeTai" ThisKey="MaDeTai" OtherKey="MaDeTai" Type="DeTai" IsForeignKey="true" />
      <Association Name="NhomSinhVien_DoAnVaDiem" Member="NhomSinhVien" ThisKey="MaNhom" OtherKey="MaNhom" Type="NhomSinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiangVien" Member="GiangViens">
    <Type Name="GiangVien">
      <Column Name="MaGiangVien" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="GiangVien_DeTai" Member="DeTais" ThisKey="MaGiangVien" OtherKey="MaGVHuongDan" Type="DeTai" />
      <Association Name="GiangVien_DeTai1" Member="DeTais1" ThisKey="MaGiangVien" OtherKey="MaGVPhanBien" Type="DeTai" />
    </Type>
  </Table>
  <Table Name="dbo.KHOA" Member="KHOAs">
    <Type Name="KHOA">
      <Column Name="MaKhoa" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KHOA_BoMon" Member="BoMons" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="BoMon" />
      <Association Name="KHOA_SinhVien" Member="SinhViens" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="SinhVien" />
    </Type>
  </Table>
  <Table Name="dbo.Lop" Member="Lops">
    <Type Name="Lop">
      <Column Name="MaLop" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Lop_SinhVien" Member="SinhViens" ThisKey="MaLop" OtherKey="MaLop" Type="SinhVien" />
    </Type>
  </Table>
  <Table Name="dbo.NhomSinhVien" Member="NhomSinhViens">
    <Type Name="NhomSinhVien">
      <Column Name="MaNhom" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Daduyet" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="MaNhomTruong" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="NhomSinhVien_DoAnVaDiem" Member="DoAnVaDiems" ThisKey="MaNhom" OtherKey="MaNhom" Type="DoAnVaDiem" />
      <Association Name="NhomSinhVien_ThanhVienNhom" Member="ThanhVienNhoms" ThisKey="MaNhom" OtherKey="Manhom" Type="ThanhVienNhom" />
      <Association Name="SinhVien_NhomSinhVien" Member="SinhVien" ThisKey="MaNhomTruong" OtherKey="MaSinhVien" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MaSinhVien" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NamSinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="SinhVien_NhomSinhVien" Member="NhomSinhViens" ThisKey="MaSinhVien" OtherKey="MaNhomTruong" Type="NhomSinhVien" />
      <Association Name="SinhVien_ThanhVienNhom" Member="ThanhVienNhoms" ThisKey="MaSinhVien" OtherKey="MaSinhVien" Type="ThanhVienNhom" />
      <Association Name="KHOA_SinhVien" Member="KHOA" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="KHOA" IsForeignKey="true" />
      <Association Name="Lop_SinhVien" Member="Lop" ThisKey="MaLop" OtherKey="MaLop" Type="Lop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhVienNhom" Member="ThanhVienNhoms">
    <Type Name="ThanhVienNhom">
      <Column Name="Manhom" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSinhVien" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NhomSinhVien_ThanhVienNhom" Member="NhomSinhVien" ThisKey="Manhom" OtherKey="MaNhom" Type="NhomSinhVien" IsForeignKey="true" />
      <Association Name="SinhVien_ThanhVienNhom" Member="SinhVien" ThisKey="MaSinhVien" OtherKey="MaSinhVien" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>