#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyDeTaiTotNghiep")]
	public partial class QLDADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBoMon(BoMon instance);
    partial void UpdateBoMon(BoMon instance);
    partial void DeleteBoMon(BoMon instance);
    partial void InsertDeTai(DeTai instance);
    partial void UpdateDeTai(DeTai instance);
    partial void DeleteDeTai(DeTai instance);
    partial void InsertDoAnVaDiem(DoAnVaDiem instance);
    partial void UpdateDoAnVaDiem(DoAnVaDiem instance);
    partial void DeleteDoAnVaDiem(DoAnVaDiem instance);
    partial void InsertGiangVien(GiangVien instance);
    partial void UpdateGiangVien(GiangVien instance);
    partial void DeleteGiangVien(GiangVien instance);
    partial void InsertKHOA(KHOA instance);
    partial void UpdateKHOA(KHOA instance);
    partial void DeleteKHOA(KHOA instance);
    partial void InsertLop(Lop instance);
    partial void UpdateLop(Lop instance);
    partial void DeleteLop(Lop instance);
    partial void InsertNhomSinhVien(NhomSinhVien instance);
    partial void UpdateNhomSinhVien(NhomSinhVien instance);
    partial void DeleteNhomSinhVien(NhomSinhVien instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    partial void InsertThanhVienNhom(ThanhVienNhom instance);
    partial void UpdateThanhVienNhom(ThanhVienNhom instance);
    partial void DeleteThanhVienNhom(ThanhVienNhom instance);
    #endregion
		
		public QLDADataContext() : 
				base(global::BUS.Properties.Settings.Default.QuanLyDeTaiTotNghiepConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BoMon> BoMons
		{
			get
			{
				return this.GetTable<BoMon>();
			}
		}
		
		public System.Data.Linq.Table<DeTai> DeTais
		{
			get
			{
				return this.GetTable<DeTai>();
			}
		}
		
		public System.Data.Linq.Table<DoAnVaDiem> DoAnVaDiems
		{
			get
			{
				return this.GetTable<DoAnVaDiem>();
			}
		}
		
		public System.Data.Linq.Table<GiangVien> GiangViens
		{
			get
			{
				return this.GetTable<GiangVien>();
			}
		}
		
		public System.Data.Linq.Table<KHOA> KHOAs
		{
			get
			{
				return this.GetTable<KHOA>();
			}
		}
		
		public System.Data.Linq.Table<Lop> Lops
		{
			get
			{
				return this.GetTable<Lop>();
			}
		}
		
		public System.Data.Linq.Table<NhomSinhVien> NhomSinhViens
		{
			get
			{
				return this.GetTable<NhomSinhVien>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
		
		public System.Data.Linq.Table<ThanhVienNhom> ThanhVienNhoms
		{
			get
			{
				return this.GetTable<ThanhVienNhom>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BoMon")]
	public partial class BoMon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBoMon;
		
		private string _TenBoMon;
		
		private string _MaKhoa;
		
		private EntitySet<DeTai> _DeTais;
		
		private EntityRef<KHOA> _KHOA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBoMonChanging(string value);
    partial void OnMaBoMonChanged();
    partial void OnTenBoMonChanging(string value);
    partial void OnTenBoMonChanged();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    #endregion
		
		public BoMon()
		{
			this._DeTais = new EntitySet<DeTai>(new Action<DeTai>(this.attach_DeTais), new Action<DeTai>(this.detach_DeTais));
			this._KHOA = default(EntityRef<KHOA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBoMon", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBoMon
		{
			get
			{
				return this._MaBoMon;
			}
			set
			{
				if ((this._MaBoMon != value))
				{
					this.OnMaBoMonChanging(value);
					this.SendPropertyChanging();
					this._MaBoMon = value;
					this.SendPropertyChanged("MaBoMon");
					this.OnMaBoMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBoMon", DbType="NVarChar(50)")]
		public string TenBoMon
		{
			get
			{
				return this._TenBoMon;
			}
			set
			{
				if ((this._TenBoMon != value))
				{
					this.OnTenBoMonChanging(value);
					this.SendPropertyChanging();
					this._TenBoMon = value;
					this.SendPropertyChanged("TenBoMon");
					this.OnTenBoMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="Char(10)")]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					if (this._KHOA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BoMon_DeTai", Storage="_DeTais", ThisKey="MaBoMon", OtherKey="MaBoMon")]
		public EntitySet<DeTai> DeTais
		{
			get
			{
				return this._DeTais;
			}
			set
			{
				this._DeTais.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOA_BoMon", Storage="_KHOA", ThisKey="MaKhoa", OtherKey="MaKhoa", IsForeignKey=true)]
		public KHOA KHOA
		{
			get
			{
				return this._KHOA.Entity;
			}
			set
			{
				KHOA previousValue = this._KHOA.Entity;
				if (((previousValue != value) 
							|| (this._KHOA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOA.Entity = null;
						previousValue.BoMons.Remove(this);
					}
					this._KHOA.Entity = value;
					if ((value != null))
					{
						value.BoMons.Add(this);
						this._MaKhoa = value.MaKhoa;
					}
					else
					{
						this._MaKhoa = default(string);
					}
					this.SendPropertyChanged("KHOA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeTais(DeTai entity)
		{
			this.SendPropertyChanging();
			entity.BoMon = this;
		}
		
		private void detach_DeTais(DeTai entity)
		{
			this.SendPropertyChanging();
			entity.BoMon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeTai")]
	public partial class DeTai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDeTai;
		
		private string _TenDeTai;
		
		private string _MoTa;
		
		private System.Nullable<byte> _TrangThai;
		
		private System.Nullable<System.DateTime> _NgayDeXuat;
		
		private System.Nullable<System.DateTime> _NgayDuyet;
		
		private string _MaGVHuongDan;
		
		private string _MaGVPhanBien;
		
		private string _MaBoMon;
		
		private EntitySet<DoAnVaDiem> _DoAnVaDiems;
		
		private EntityRef<BoMon> _BoMon;
		
		private EntityRef<GiangVien> _GiangVien;
		
		private EntityRef<GiangVien> _GiangVien1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDeTaiChanging(string value);
    partial void OnMaDeTaiChanged();
    partial void OnTenDeTaiChanging(string value);
    partial void OnTenDeTaiChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnTrangThaiChanging(System.Nullable<byte> value);
    partial void OnTrangThaiChanged();
    partial void OnNgayDeXuatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDeXuatChanged();
    partial void OnNgayDuyetChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDuyetChanged();
    partial void OnMaGVHuongDanChanging(string value);
    partial void OnMaGVHuongDanChanged();
    partial void OnMaGVPhanBienChanging(string value);
    partial void OnMaGVPhanBienChanged();
    partial void OnMaBoMonChanging(string value);
    partial void OnMaBoMonChanged();
    #endregion
		
		public DeTai()
		{
			this._DoAnVaDiems = new EntitySet<DoAnVaDiem>(new Action<DoAnVaDiem>(this.attach_DoAnVaDiems), new Action<DoAnVaDiem>(this.detach_DoAnVaDiems));
			this._BoMon = default(EntityRef<BoMon>);
			this._GiangVien = default(EntityRef<GiangVien>);
			this._GiangVien1 = default(EntityRef<GiangVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDeTai", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDeTai
		{
			get
			{
				return this._MaDeTai;
			}
			set
			{
				if ((this._MaDeTai != value))
				{
					this.OnMaDeTaiChanging(value);
					this.SendPropertyChanging();
					this._MaDeTai = value;
					this.SendPropertyChanged("MaDeTai");
					this.OnMaDeTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDeTai", DbType="NVarChar(100)")]
		public string TenDeTai
		{
			get
			{
				return this._TenDeTai;
			}
			set
			{
				if ((this._TenDeTai != value))
				{
					this.OnTenDeTaiChanging(value);
					this.SendPropertyChanging();
					this._TenDeTai = value;
					this.SendPropertyChanged("TenDeTai");
					this.OnTenDeTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(255)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="TinyInt")]
		public System.Nullable<byte> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDeXuat", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDeXuat
		{
			get
			{
				return this._NgayDeXuat;
			}
			set
			{
				if ((this._NgayDeXuat != value))
				{
					this.OnNgayDeXuatChanging(value);
					this.SendPropertyChanging();
					this._NgayDeXuat = value;
					this.SendPropertyChanged("NgayDeXuat");
					this.OnNgayDeXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDuyet", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDuyet
		{
			get
			{
				return this._NgayDuyet;
			}
			set
			{
				if ((this._NgayDuyet != value))
				{
					this.OnNgayDuyetChanging(value);
					this.SendPropertyChanging();
					this._NgayDuyet = value;
					this.SendPropertyChanged("NgayDuyet");
					this.OnNgayDuyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGVHuongDan", DbType="Char(5)")]
		public string MaGVHuongDan
		{
			get
			{
				return this._MaGVHuongDan;
			}
			set
			{
				if ((this._MaGVHuongDan != value))
				{
					if (this._GiangVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGVHuongDanChanging(value);
					this.SendPropertyChanging();
					this._MaGVHuongDan = value;
					this.SendPropertyChanged("MaGVHuongDan");
					this.OnMaGVHuongDanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGVPhanBien", DbType="Char(5)")]
		public string MaGVPhanBien
		{
			get
			{
				return this._MaGVPhanBien;
			}
			set
			{
				if ((this._MaGVPhanBien != value))
				{
					if (this._GiangVien1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGVPhanBienChanging(value);
					this.SendPropertyChanging();
					this._MaGVPhanBien = value;
					this.SendPropertyChanged("MaGVPhanBien");
					this.OnMaGVPhanBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBoMon", DbType="Char(10)")]
		public string MaBoMon
		{
			get
			{
				return this._MaBoMon;
			}
			set
			{
				if ((this._MaBoMon != value))
				{
					if (this._BoMon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBoMonChanging(value);
					this.SendPropertyChanging();
					this._MaBoMon = value;
					this.SendPropertyChanged("MaBoMon");
					this.OnMaBoMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeTai_DoAnVaDiem", Storage="_DoAnVaDiems", ThisKey="MaDeTai", OtherKey="MaDeTai")]
		public EntitySet<DoAnVaDiem> DoAnVaDiems
		{
			get
			{
				return this._DoAnVaDiems;
			}
			set
			{
				this._DoAnVaDiems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BoMon_DeTai", Storage="_BoMon", ThisKey="MaBoMon", OtherKey="MaBoMon", IsForeignKey=true)]
		public BoMon BoMon
		{
			get
			{
				return this._BoMon.Entity;
			}
			set
			{
				BoMon previousValue = this._BoMon.Entity;
				if (((previousValue != value) 
							|| (this._BoMon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BoMon.Entity = null;
						previousValue.DeTais.Remove(this);
					}
					this._BoMon.Entity = value;
					if ((value != null))
					{
						value.DeTais.Add(this);
						this._MaBoMon = value.MaBoMon;
					}
					else
					{
						this._MaBoMon = default(string);
					}
					this.SendPropertyChanged("BoMon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_DeTai", Storage="_GiangVien", ThisKey="MaGVHuongDan", OtherKey="MaGiangVien", IsForeignKey=true)]
		public GiangVien GiangVien
		{
			get
			{
				return this._GiangVien.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien.Entity = null;
						previousValue.DeTais.Remove(this);
					}
					this._GiangVien.Entity = value;
					if ((value != null))
					{
						value.DeTais.Add(this);
						this._MaGVHuongDan = value.MaGiangVien;
					}
					else
					{
						this._MaGVHuongDan = default(string);
					}
					this.SendPropertyChanged("GiangVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_DeTai1", Storage="_GiangVien1", ThisKey="MaGVPhanBien", OtherKey="MaGiangVien", IsForeignKey=true)]
		public GiangVien GiangVien1
		{
			get
			{
				return this._GiangVien1.Entity;
			}
			set
			{
				GiangVien previousValue = this._GiangVien1.Entity;
				if (((previousValue != value) 
							|| (this._GiangVien1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiangVien1.Entity = null;
						previousValue.DeTais1.Remove(this);
					}
					this._GiangVien1.Entity = value;
					if ((value != null))
					{
						value.DeTais1.Add(this);
						this._MaGVPhanBien = value.MaGiangVien;
					}
					else
					{
						this._MaGVPhanBien = default(string);
					}
					this.SendPropertyChanged("GiangVien1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DoAnVaDiems(DoAnVaDiem entity)
		{
			this.SendPropertyChanging();
			entity.DeTai = this;
		}
		
		private void detach_DoAnVaDiems(DoAnVaDiem entity)
		{
			this.SendPropertyChanging();
			entity.DeTai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DoAnVaDiem")]
	public partial class DoAnVaDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDeTai;
		
		private string _Id;
		
		private System.Nullable<System.DateTime> _NgayNopDoAn;
		
		private string _NoiDungDoAn;
		
		private System.Nullable<double> _DiemGVHuongDan;
		
		private System.Nullable<double> _DiemGVPhanBien;
		
		private System.Nullable<double> _DiemCuoiCung;
		
		private string _NhanXet;
		
		private System.Nullable<System.DateTime> _NgayCham;
		
		private string _MaNhom;
		
		private EntityRef<DeTai> _DeTai;
		
		private EntityRef<NhomSinhVien> _NhomSinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDeTaiChanging(string value);
    partial void OnMaDeTaiChanged();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnNgayNopDoAnChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNopDoAnChanged();
    partial void OnNoiDungDoAnChanging(string value);
    partial void OnNoiDungDoAnChanged();
    partial void OnDiemGVHuongDanChanging(System.Nullable<double> value);
    partial void OnDiemGVHuongDanChanged();
    partial void OnDiemGVPhanBienChanging(System.Nullable<double> value);
    partial void OnDiemGVPhanBienChanged();
    partial void OnDiemCuoiCungChanging(System.Nullable<double> value);
    partial void OnDiemCuoiCungChanged();
    partial void OnNhanXetChanging(string value);
    partial void OnNhanXetChanged();
    partial void OnNgayChamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChamChanged();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    #endregion
		
		public DoAnVaDiem()
		{
			this._DeTai = default(EntityRef<DeTai>);
			this._NhomSinhVien = default(EntityRef<NhomSinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDeTai", DbType="Char(10)")]
		public string MaDeTai
		{
			get
			{
				return this._MaDeTai;
			}
			set
			{
				if ((this._MaDeTai != value))
				{
					if (this._DeTai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDeTaiChanging(value);
					this.SendPropertyChanging();
					this._MaDeTai = value;
					this.SendPropertyChanged("MaDeTai");
					this.OnMaDeTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNopDoAn", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayNopDoAn
		{
			get
			{
				return this._NgayNopDoAn;
			}
			set
			{
				if ((this._NgayNopDoAn != value))
				{
					this.OnNgayNopDoAnChanging(value);
					this.SendPropertyChanging();
					this._NgayNopDoAn = value;
					this.SendPropertyChanged("NgayNopDoAn");
					this.OnNgayNopDoAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungDoAn", DbType="NVarChar(255)")]
		public string NoiDungDoAn
		{
			get
			{
				return this._NoiDungDoAn;
			}
			set
			{
				if ((this._NoiDungDoAn != value))
				{
					this.OnNoiDungDoAnChanging(value);
					this.SendPropertyChanging();
					this._NoiDungDoAn = value;
					this.SendPropertyChanged("NoiDungDoAn");
					this.OnNoiDungDoAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemGVHuongDan", DbType="Float")]
		public System.Nullable<double> DiemGVHuongDan
		{
			get
			{
				return this._DiemGVHuongDan;
			}
			set
			{
				if ((this._DiemGVHuongDan != value))
				{
					this.OnDiemGVHuongDanChanging(value);
					this.SendPropertyChanging();
					this._DiemGVHuongDan = value;
					this.SendPropertyChanged("DiemGVHuongDan");
					this.OnDiemGVHuongDanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemGVPhanBien", DbType="Float")]
		public System.Nullable<double> DiemGVPhanBien
		{
			get
			{
				return this._DiemGVPhanBien;
			}
			set
			{
				if ((this._DiemGVPhanBien != value))
				{
					this.OnDiemGVPhanBienChanging(value);
					this.SendPropertyChanging();
					this._DiemGVPhanBien = value;
					this.SendPropertyChanged("DiemGVPhanBien");
					this.OnDiemGVPhanBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemCuoiCung", DbType="Float")]
		public System.Nullable<double> DiemCuoiCung
		{
			get
			{
				return this._DiemCuoiCung;
			}
			set
			{
				if ((this._DiemCuoiCung != value))
				{
					this.OnDiemCuoiCungChanging(value);
					this.SendPropertyChanging();
					this._DiemCuoiCung = value;
					this.SendPropertyChanged("DiemCuoiCung");
					this.OnDiemCuoiCungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanXet", DbType="NVarChar(255)")]
		public string NhanXet
		{
			get
			{
				return this._NhanXet;
			}
			set
			{
				if ((this._NhanXet != value))
				{
					this.OnNhanXetChanging(value);
					this.SendPropertyChanging();
					this._NhanXet = value;
					this.SendPropertyChanged("NhanXet");
					this.OnNhanXetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCham", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayCham
		{
			get
			{
				return this._NgayCham;
			}
			set
			{
				if ((this._NgayCham != value))
				{
					this.OnNgayChamChanging(value);
					this.SendPropertyChanging();
					this._NgayCham = value;
					this.SendPropertyChanged("NgayCham");
					this.OnNgayChamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Char(10)")]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._NhomSinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeTai_DoAnVaDiem", Storage="_DeTai", ThisKey="MaDeTai", OtherKey="MaDeTai", IsForeignKey=true)]
		public DeTai DeTai
		{
			get
			{
				return this._DeTai.Entity;
			}
			set
			{
				DeTai previousValue = this._DeTai.Entity;
				if (((previousValue != value) 
							|| (this._DeTai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeTai.Entity = null;
						previousValue.DoAnVaDiems.Remove(this);
					}
					this._DeTai.Entity = value;
					if ((value != null))
					{
						value.DoAnVaDiems.Add(this);
						this._MaDeTai = value.MaDeTai;
					}
					else
					{
						this._MaDeTai = default(string);
					}
					this.SendPropertyChanged("DeTai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSinhVien_DoAnVaDiem", Storage="_NhomSinhVien", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public NhomSinhVien NhomSinhVien
		{
			get
			{
				return this._NhomSinhVien.Entity;
			}
			set
			{
				NhomSinhVien previousValue = this._NhomSinhVien.Entity;
				if (((previousValue != value) 
							|| (this._NhomSinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomSinhVien.Entity = null;
						previousValue.DoAnVaDiems.Remove(this);
					}
					this._NhomSinhVien.Entity = value;
					if ((value != null))
					{
						value.DoAnVaDiems.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("NhomSinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiangVien")]
	public partial class GiangVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiangVien;
		
		private string _HoTen;
		
		private string _Email;
		
		private string _SoDienThoai;
		
		private string _TenDangNhap;
		
		private EntitySet<DeTai> _DeTais;
		
		private EntitySet<DeTai> _DeTais1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiangVienChanging(string value);
    partial void OnMaGiangVienChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    #endregion
		
		public GiangVien()
		{
			this._DeTais = new EntitySet<DeTai>(new Action<DeTai>(this.attach_DeTais), new Action<DeTai>(this.detach_DeTais));
			this._DeTais1 = new EntitySet<DeTai>(new Action<DeTai>(this.attach_DeTais1), new Action<DeTai>(this.detach_DeTais1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiangVien", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiangVien
		{
			get
			{
				return this._MaGiangVien;
			}
			set
			{
				if ((this._MaGiangVien != value))
				{
					this.OnMaGiangVienChanging(value);
					this.SendPropertyChanging();
					this._MaGiangVien = value;
					this.SendPropertyChanged("MaGiangVien");
					this.OnMaGiangVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(12)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_DeTai", Storage="_DeTais", ThisKey="MaGiangVien", OtherKey="MaGVHuongDan")]
		public EntitySet<DeTai> DeTais
		{
			get
			{
				return this._DeTais;
			}
			set
			{
				this._DeTais.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiangVien_DeTai1", Storage="_DeTais1", ThisKey="MaGiangVien", OtherKey="MaGVPhanBien")]
		public EntitySet<DeTai> DeTais1
		{
			get
			{
				return this._DeTais1;
			}
			set
			{
				this._DeTais1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeTais(DeTai entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = this;
		}
		
		private void detach_DeTais(DeTai entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien = null;
		}
		
		private void attach_DeTais1(DeTai entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien1 = this;
		}
		
		private void detach_DeTais1(DeTai entity)
		{
			this.SendPropertyChanging();
			entity.GiangVien1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHOA")]
	public partial class KHOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhoa;
		
		private string _TenKhoa;
		
		private EntitySet<BoMon> _BoMons;
		
		private EntitySet<SinhVien> _SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnTenKhoaChanging(string value);
    partial void OnTenKhoaChanged();
    #endregion
		
		public KHOA()
		{
			this._BoMons = new EntitySet<BoMon>(new Action<BoMon>(this.attach_BoMons), new Action<BoMon>(this.detach_BoMons));
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoa", DbType="NVarChar(50)")]
		public string TenKhoa
		{
			get
			{
				return this._TenKhoa;
			}
			set
			{
				if ((this._TenKhoa != value))
				{
					this.OnTenKhoaChanging(value);
					this.SendPropertyChanging();
					this._TenKhoa = value;
					this.SendPropertyChanged("TenKhoa");
					this.OnTenKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOA_BoMon", Storage="_BoMons", ThisKey="MaKhoa", OtherKey="MaKhoa")]
		public EntitySet<BoMon> BoMons
		{
			get
			{
				return this._BoMons;
			}
			set
			{
				this._BoMons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOA_SinhVien", Storage="_SinhViens", ThisKey="MaKhoa", OtherKey="MaKhoa")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BoMons(BoMon entity)
		{
			this.SendPropertyChanging();
			entity.KHOA = this;
		}
		
		private void detach_BoMons(BoMon entity)
		{
			this.SendPropertyChanging();
			entity.KHOA = null;
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.KHOA = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.KHOA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lop")]
	public partial class Lop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLop;
		
		private string _TenLop;
		
		private EntitySet<SinhVien> _SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnTenLopChanging(string value);
    partial void OnTenLopChanged();
    #endregion
		
		public Lop()
		{
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this.OnTenLopChanging(value);
					this.SendPropertyChanging();
					this._TenLop = value;
					this.SendPropertyChanged("TenLop");
					this.OnTenLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_SinhVien", Storage="_SinhViens", ThisKey="MaLop", OtherKey="MaLop")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Lop = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Lop = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomSinhVien")]
	public partial class NhomSinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private System.Nullable<System.DateTime> _NgayDangKy;
		
		private System.Nullable<byte> _Daduyet;
		
		private string _MaNhomTruong;
		
		private EntitySet<DoAnVaDiem> _DoAnVaDiems;
		
		private EntitySet<ThanhVienNhom> _ThanhVienNhoms;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnNgayDangKyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangKyChanged();
    partial void OnDaduyetChanging(System.Nullable<byte> value);
    partial void OnDaduyetChanged();
    partial void OnMaNhomTruongChanging(string value);
    partial void OnMaNhomTruongChanged();
    #endregion
		
		public NhomSinhVien()
		{
			this._DoAnVaDiems = new EntitySet<DoAnVaDiem>(new Action<DoAnVaDiem>(this.attach_DoAnVaDiems), new Action<DoAnVaDiem>(this.detach_DoAnVaDiems));
			this._ThanhVienNhoms = new EntitySet<ThanhVienNhom>(new Action<ThanhVienNhom>(this.attach_ThanhVienNhoms), new Action<ThanhVienNhom>(this.detach_ThanhVienNhoms));
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDangKy
		{
			get
			{
				return this._NgayDangKy;
			}
			set
			{
				if ((this._NgayDangKy != value))
				{
					this.OnNgayDangKyChanging(value);
					this.SendPropertyChanging();
					this._NgayDangKy = value;
					this.SendPropertyChanged("NgayDangKy");
					this.OnNgayDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Daduyet", DbType="TinyInt")]
		public System.Nullable<byte> Daduyet
		{
			get
			{
				return this._Daduyet;
			}
			set
			{
				if ((this._Daduyet != value))
				{
					this.OnDaduyetChanging(value);
					this.SendPropertyChanging();
					this._Daduyet = value;
					this.SendPropertyChanged("Daduyet");
					this.OnDaduyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomTruong", DbType="Char(10)")]
		public string MaNhomTruong
		{
			get
			{
				return this._MaNhomTruong;
			}
			set
			{
				if ((this._MaNhomTruong != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomTruongChanging(value);
					this.SendPropertyChanging();
					this._MaNhomTruong = value;
					this.SendPropertyChanged("MaNhomTruong");
					this.OnMaNhomTruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSinhVien_DoAnVaDiem", Storage="_DoAnVaDiems", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<DoAnVaDiem> DoAnVaDiems
		{
			get
			{
				return this._DoAnVaDiems;
			}
			set
			{
				this._DoAnVaDiems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSinhVien_ThanhVienNhom", Storage="_ThanhVienNhoms", ThisKey="MaNhom", OtherKey="Manhom")]
		public EntitySet<ThanhVienNhom> ThanhVienNhoms
		{
			get
			{
				return this._ThanhVienNhoms;
			}
			set
			{
				this._ThanhVienNhoms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_NhomSinhVien", Storage="_SinhVien", ThisKey="MaNhomTruong", OtherKey="MaSinhVien", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.NhomSinhViens.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.NhomSinhViens.Add(this);
						this._MaNhomTruong = value.MaSinhVien;
					}
					else
					{
						this._MaNhomTruong = default(string);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DoAnVaDiems(DoAnVaDiem entity)
		{
			this.SendPropertyChanging();
			entity.NhomSinhVien = this;
		}
		
		private void detach_DoAnVaDiems(DoAnVaDiem entity)
		{
			this.SendPropertyChanging();
			entity.NhomSinhVien = null;
		}
		
		private void attach_ThanhVienNhoms(ThanhVienNhom entity)
		{
			this.SendPropertyChanging();
			entity.NhomSinhVien = this;
		}
		
		private void detach_ThanhVienNhoms(ThanhVienNhom entity)
		{
			this.SendPropertyChanging();
			entity.NhomSinhVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSinhVien;
		
		private string _HoTen;
		
		private System.Nullable<byte> _GioiTinh;
		
		private System.Nullable<System.DateTime> _NamSinh;
		
		private string _Email;
		
		private string _SoDienThoai;
		
		private string _MaLop;
		
		private string _MaKhoa;
		
		private string _TenDangNhap;
		
		private EntitySet<NhomSinhVien> _NhomSinhViens;
		
		private EntitySet<ThanhVienNhom> _ThanhVienNhoms;
		
		private EntityRef<KHOA> _KHOA;
		
		private EntityRef<Lop> _Lop;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSinhVienChanging(string value);
    partial void OnMaSinhVienChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(System.Nullable<byte> value);
    partial void OnGioiTinhChanged();
    partial void OnNamSinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNamSinhChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnMaLopChanging(string value);
    partial void OnMaLopChanged();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    #endregion
		
		public SinhVien()
		{
			this._NhomSinhViens = new EntitySet<NhomSinhVien>(new Action<NhomSinhVien>(this.attach_NhomSinhViens), new Action<NhomSinhVien>(this.detach_NhomSinhViens));
			this._ThanhVienNhoms = new EntitySet<ThanhVienNhom>(new Action<ThanhVienNhom>(this.attach_ThanhVienNhoms), new Action<ThanhVienNhom>(this.detach_ThanhVienNhoms));
			this._KHOA = default(EntityRef<KHOA>);
			this._Lop = default(EntityRef<Lop>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSinhVien", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSinhVien
		{
			get
			{
				return this._MaSinhVien;
			}
			set
			{
				if ((this._MaSinhVien != value))
				{
					this.OnMaSinhVienChanging(value);
					this.SendPropertyChanging();
					this._MaSinhVien = value;
					this.SendPropertyChanged("MaSinhVien");
					this.OnMaSinhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="TinyInt")]
		public System.Nullable<byte> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="Date")]
		public System.Nullable<System.DateTime> NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this.OnNamSinhChanging(value);
					this.SendPropertyChanging();
					this._NamSinh = value;
					this.SendPropertyChanged("NamSinh");
					this.OnNamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(12)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLop", DbType="Char(10)")]
		public string MaLop
		{
			get
			{
				return this._MaLop;
			}
			set
			{
				if ((this._MaLop != value))
				{
					if (this._Lop.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLopChanging(value);
					this.SendPropertyChanging();
					this._MaLop = value;
					this.SendPropertyChanged("MaLop");
					this.OnMaLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="Char(10)")]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					if (this._KHOA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_NhomSinhVien", Storage="_NhomSinhViens", ThisKey="MaSinhVien", OtherKey="MaNhomTruong")]
		public EntitySet<NhomSinhVien> NhomSinhViens
		{
			get
			{
				return this._NhomSinhViens;
			}
			set
			{
				this._NhomSinhViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_ThanhVienNhom", Storage="_ThanhVienNhoms", ThisKey="MaSinhVien", OtherKey="MaSinhVien")]
		public EntitySet<ThanhVienNhom> ThanhVienNhoms
		{
			get
			{
				return this._ThanhVienNhoms;
			}
			set
			{
				this._ThanhVienNhoms.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOA_SinhVien", Storage="_KHOA", ThisKey="MaKhoa", OtherKey="MaKhoa", IsForeignKey=true)]
		public KHOA KHOA
		{
			get
			{
				return this._KHOA.Entity;
			}
			set
			{
				KHOA previousValue = this._KHOA.Entity;
				if (((previousValue != value) 
							|| (this._KHOA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOA.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._KHOA.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._MaKhoa = value.MaKhoa;
					}
					else
					{
						this._MaKhoa = default(string);
					}
					this.SendPropertyChanged("KHOA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Lop_SinhVien", Storage="_Lop", ThisKey="MaLop", OtherKey="MaLop", IsForeignKey=true)]
		public Lop Lop
		{
			get
			{
				return this._Lop.Entity;
			}
			set
			{
				Lop previousValue = this._Lop.Entity;
				if (((previousValue != value) 
							|| (this._Lop.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Lop.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._Lop.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._MaLop = value.MaLop;
					}
					else
					{
						this._MaLop = default(string);
					}
					this.SendPropertyChanged("Lop");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhomSinhViens(NhomSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_NhomSinhViens(NhomSinhVien entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
		
		private void attach_ThanhVienNhoms(ThanhVienNhom entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = this;
		}
		
		private void detach_ThanhVienNhoms(ThanhVienNhom entity)
		{
			this.SendPropertyChanging();
			entity.SinhVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhVienNhom")]
	public partial class ThanhVienNhom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Manhom;
		
		private string _MaSinhVien;
		
		private EntityRef<NhomSinhVien> _NhomSinhVien;
		
		private EntityRef<SinhVien> _SinhVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManhomChanging(string value);
    partial void OnManhomChanged();
    partial void OnMaSinhVienChanging(string value);
    partial void OnMaSinhVienChanged();
    #endregion
		
		public ThanhVienNhom()
		{
			this._NhomSinhVien = default(EntityRef<NhomSinhVien>);
			this._SinhVien = default(EntityRef<SinhVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhom", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Manhom
		{
			get
			{
				return this._Manhom;
			}
			set
			{
				if ((this._Manhom != value))
				{
					if (this._NhomSinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnManhomChanging(value);
					this.SendPropertyChanging();
					this._Manhom = value;
					this.SendPropertyChanged("Manhom");
					this.OnManhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSinhVien", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSinhVien
		{
			get
			{
				return this._MaSinhVien;
			}
			set
			{
				if ((this._MaSinhVien != value))
				{
					if (this._SinhVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSinhVienChanging(value);
					this.SendPropertyChanging();
					this._MaSinhVien = value;
					this.SendPropertyChanged("MaSinhVien");
					this.OnMaSinhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSinhVien_ThanhVienNhom", Storage="_NhomSinhVien", ThisKey="Manhom", OtherKey="MaNhom", IsForeignKey=true)]
		public NhomSinhVien NhomSinhVien
		{
			get
			{
				return this._NhomSinhVien.Entity;
			}
			set
			{
				NhomSinhVien previousValue = this._NhomSinhVien.Entity;
				if (((previousValue != value) 
							|| (this._NhomSinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomSinhVien.Entity = null;
						previousValue.ThanhVienNhoms.Remove(this);
					}
					this._NhomSinhVien.Entity = value;
					if ((value != null))
					{
						value.ThanhVienNhoms.Add(this);
						this._Manhom = value.MaNhom;
					}
					else
					{
						this._Manhom = default(string);
					}
					this.SendPropertyChanged("NhomSinhVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SinhVien_ThanhVienNhom", Storage="_SinhVien", ThisKey="MaSinhVien", OtherKey="MaSinhVien", IsForeignKey=true)]
		public SinhVien SinhVien
		{
			get
			{
				return this._SinhVien.Entity;
			}
			set
			{
				SinhVien previousValue = this._SinhVien.Entity;
				if (((previousValue != value) 
							|| (this._SinhVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SinhVien.Entity = null;
						previousValue.ThanhVienNhoms.Remove(this);
					}
					this._SinhVien.Entity = value;
					if ((value != null))
					{
						value.ThanhVienNhoms.Add(this);
						this._MaSinhVien = value.MaSinhVien;
					}
					else
					{
						this._MaSinhVien = default(string);
					}
					this.SendPropertyChanged("SinhVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
